name: Latest statistics workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.10
          architecture: x64
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Update README
        run: |-
          python fetcher.py
          cat README.md
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "readme-bot@uselessxiv.com"
          git config --global user.name "checker-bot"
          git add -A
          git commit -m "Updated content" || exit 0
          git push


          